core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views #

from . import views

urlpatterns = [
	path('', views.index, name="index"),
	path('todo/@<user>/<pk>/', views.todoPage, name="todo"),
	path('category/', views.category, name="category"),
	path('category/<pk>/<name>/', views.categoryPage, name="cat"),
	path('search/', views.search, name="search"),

	path('createTodo/', views.createTodo, name="todo-create"),
	path('updateTodo/<pk>/', views.updateTodo, name="todo-update"),
	path('deleteTodo/<pk>/', views.TodoDelete.as_view(), name="todo-delete"),

	path('createCategory/', views.CategoryCreate.as_view(), name="category-create"),
	path('updateCategory/<pk>/', views.CategoryUpdate.as_view(), name="category-update"),
	path('deleteCategory/<pk>/', views.CategoryDelete.as_view(), name="category-delete"),

	path('register/', views.register, name="register"),
	path('login/', views.signin, name="login"),
	path('logout/', views.signout, name="logout"),
	path('profile/', views.userProfile, name="profile"),

	path('auth/reset_password/',auth_views.PasswordResetView.as_view(template_name="auth/password_reset.html"),name="reset_password"),
	path('auth/reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="auth/password_done.html"), name="password_reset_done"),
	path('auth/reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="auth/password_confirm.html"), name="password_reset_confirm"),
	path('auth/reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="auth/password_complete.html"), name="password_reset_complete"),


]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

ALERTS = (
    ("primary", "Blue"),  # Key, Value
    ("secondary", "Grey"),
    ("danger", "Red"),
    ("info", "Sky Blue"),
    ("success", "Green"),
    ("warning", "Yellow"),
    ("dark", "Black"),
)


# Model for Category Objects
class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(null=True, max_length=100, verbose_name="Category Name")
    color = models.CharField(null=True, max_length=50, choices=ALERTS)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"  # Plural Form of Model

    # Redirect User to this url, if form is created or updated
    def get_absolute_url(self):
        return reverse("cat", kwargs={"pk": self.pk, "name": self.name})


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(null=True, max_length=300, verbose_name="To-Do Name", help_text="Please Type your Todo")
    description = models.TextField(null=True, verbose_name="To-Do Description", blank=True, help_text="Optional")
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, null=True, blank=True, help_text="Optional")
    start_date = models.DateTimeField(auto_now_add=True, null=True)
    end_date = models.DateField(null=True, blank=True, help_text="Optional: Type this if you want this todo to expire")
    expired = models.BooleanField(null=True, default=False)
    completed = models.BooleanField(null=True, default=False, verbose_name="Completed Todo",
                                    help_text="Optional: Only use this when you have completed your todo!")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-start_date"]

core/forms.py
from django import forms
from django.forms import ModelForm

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Todo, Category


# Form that Extends Users Default Registration Form
class UserForm(UserCreationForm):
    class Meta:
        model = User  # Model to Extend/ Inherit
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]  # Fields needed

        # Helpful Information given to users when completing form
        help_texts = {
            "username": "Username should be more than 30 characters",
            "email": "We are just using this, in case you forget your password!",
            "first_name": "Enter your First Name",
            "last_name": "Enter your Last Name",
        }


# Form for User Settings
class UserProfileForm(ModelForm):
    class Meta:
        model = User
        fields = "__all__"


class DateInput(forms.DateInput):
    input_type = "date"


# Form for Todo
class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ["id", "name", "category", "end_date", "description", "completed"]
        widgets = {"end_date": DateInput()}

    # Sort Categories according to User
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["category"].queryset = Category.objects.filter(user=user)

    # Validates Form
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

core/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import *
from .models import *


# Home Page
@login_required(login_url='login')  # User must be authenticated before access to this page
def index(request):
    todos = Todo.objects.order_by("-start_date").filter(user=request.user, expired=False,
                                                        completed=False)  # Unexpired, Uncompleted Todo
    expired_todo = Todo.objects.order_by("-start_date").filter(user=request.user, expired=True)  # Expired Todo
    completed_todo = Todo.objects.order_by("-start_date").filter(user=request.user, expired=False,
                                                                 completed=True)  # Completed Todo
    frontend = {  # Passing Models to Frontend
        "todos": todos,
        "completed_todo": completed_todo,
        "expired_todo": expired_todo,
    }
    return render(request, 'core/index.html', frontend)


# Page for a specific todo
def todoPage(request, user, pk):
    # If Todo Object Exist Show Else Spit Error
    todo = get_object_or_404(Todo, pk=pk, user=request.user)
    frontend = {
        "todo": todo,
    }
    return render(request, 'core/todo.html', frontend)


# Summary of Categories for a User
def category(request):
    categories = Category.objects.filter(user=request.user)  # Sort Category by Authenticated User
    frontend = {
        "categories": categories,
    }
    return render(request, 'core/category.html', frontend)


# Single Page for Specific Category
def categoryPage(request, pk, name):
    category = get_object_or_404(Category, pk=pk, name=name)
    frontend = {
        "category": category,
    }
    return render(request, 'core/category-page.html', frontend)


# Search Functionality
def search(request):
    # Create a Variable and Store All Todo Objects in it
    query = Todo.objects.order_by("-start_date").filter(user=request.user, expired=False)

    # Keyword is the search name from the front-end
    if "keyword" in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            # Sort Keyword to match Query
            query = query.filter(description__icontains=keyword) or query.filter(name__icontains=keyword)
    keyword = request.GET['keyword']

    frontend = {
        "keyword": keyword,
        "query": query,
    }
    return render(request, 'core/search.html', frontend)


# Creating Todo Application
def createTodo(request):
    if request.method == "POST":  # If Request Method is POST
        # Save the User and Form Data into Form
        form = TodoForm(request.user, request.POST)
        # Check If Form is Valid
        if form.is_valid():
            todo = form.save()
            todo.user = request.user  # Save Authenticated User as User of Form
            todo.save()  # Save Form
            messages.success(request, "Todo successfully created!")  # Send a Success Message
            return redirect('todo', user=request.user, pk=todo.pk)  # Redirect to Single Todo Page
    else:
        form = TodoForm(request.user)
    frontend = {"form": form}
    return render(request, 'core/todo-create.html', frontend)


# Updating Todo App
def updateTodo(request, pk):
    todo = Todo.objects.get(pk=pk)  # Find Todo Object that matches id of url
    if request.method == "POST":
        #  When Form Id is found, Update existing fields
        form = TodoForm(user=request.user, data=request.POST, instance=todo)
        if form.is_valid():
            bar = form.save()
            bar.save()
            messages.success(request, "Todo successfully updated")
            return redirect('todo', user=request.user, pk=bar.pk)  # Redirect to Single Todo Page
    else:
        form = TodoForm(user=request.user, instance=todo)
    frontend = {
        "form": form
    }
    return render(request, "core/todo-update.html", frontend)


# Deleting the todo, Login is Required
class TodoDelete(LoginRequiredMixin, DeleteView):
    model = Todo
    success_message = "Todo was deleted successfully!"
    success_url = reverse_lazy('index')  # Redirects to this page
    template_name = "core/app_delete.html"

    # Method to Activate "success_message" variable above
    def delete(self, request, *args, **kwargs):
        messages.info(self.request, self.success_message)
        return super(TodoDelete, self).delete(request, *args, **kwargs)


# Creating a New Category Object
class CategoryCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Category
    fields = ['name', "color"]
    template_name = "core/category-create.html"
    success_message = "Category was created successfully!"

    # Validates Form
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


# Updating a Category
class CategoryUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Category
    fields = ['name', "color"]
    template_name = "core/category-update.html"
    success_message = "Category was updated successfully!"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


# Deleting a Category
class CategoryDelete(LoginRequiredMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('index')
    template_name = "core/app_delete.html"
    success_message = "Category was deleted successfully!"

    def delete(self, request, *args, **kwargs):
        messages.info(self.request, self.success_message)
        return super(CategoryDelete, self).delete(request, *args, **kwargs)


# Registration Form for User
def register(request):
    form = UserForm()  # Creating an instance of the form
    if request.method == "POST":
        user = UserForm(request.POST)  # Saving Data into form
        if user.is_valid():
            user.save()
            username = user.cleaned_data['username']  # Collecting Username of the Newly Created user
            messages.success(request, f"Welcome New User {username}")  # Sending message
            return redirect("login")
        else:
            # Sending any  error to user
            for msg in user.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")
    frontend = {"form": form}
    return render(request, "core/register.html", frontend)


# Login Form/ Page for User
def signin(request):
    if request.method == "POST":
        username = request.POST["username"]  # Collect Username from frontend
        password = request.POST["password"]  # Collect password from frontend
        user = authenticate(request, username=username, password=password)  # Verify User
        if user is not None:  # If User Exists
            login(request, user)  # Login User
            messages.success(request, f"Welcome {username} !")
            return redirect("index")
        else:
            messages.error(request, "Invalid Credentials")
    return render(request, "core/login.html")


# Sign Out USer
def signout(request):
    if request.method == "POST":
        logout(request)
        messages.info(request, "Succesfully Logged Out, Love to see you again!!")
        return redirect("login")


# Page for User to Change their Names etc
def userProfile(request):
    user = request.user
    form = UserProfileForm(instance=user)
    frontend = {"form": form}

    if request.method == "POST":
        form = UserProfileForm(request.POST, instance=user)
        if form.is_valid:
            form.save()
            messages.success(request, f"Your Profile was successfully updated, {user}")
    return render(request, "core/settings.html", frontend)

templates/core/app_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Confirm Delete
{% endblock %}
{% block content %} 
<div class="container">
	<br>
  <div class="row">
    <div class="col-md-6 mx-auto">
      <div class="card">
        <div class="card-header text-white bg-primary">
          <h4 class="text-center">Confirm Delete</h4></div>
          <div class="card-body">
            <form action="" method="post" accept-charset="utf-8">
              <h3 class="text-center">Are you sure you want to delete?</h1>
              {% csrf_token %}
              {{form|crispy}}
              <div class="form-group">
                <div class="row">
                  <div class="col-xs-6 mx-auto text-center">
                    <button type="submit" class="btn text-white bg-danger">Delete</button>
                  </div>
                  <div class="col-xs-6 mx-auto text-center">
                    <a href="#" class="btn text-white bg-primary " id="close-window">Cancel</a>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>

<script type="text/javascript">
  document.getElementById('close-window').addEventListener("click", function() {
    window.close();
  })
</script>
{% endblock %}

templates/core/category-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="col-md-6 mx-auto pt-3">
      <div class="card">
        <div class="card-header text-white bg-primary ">
          <h4 class="text-center"><i class="fas fa-plus"></i> Create Category</h4></div>
          <div class="card-body">
            <form method="post" accept-charset="utf-8">
              {% csrf_token %}
              {{form|crispy}}
              <div class="form-group">
                <div class="mx-auto">
                  <button type="submit" class="btn btn-block btn-sm text-white bg-primary">Create</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/core/category-page.html
{% extends 'base.html' %}
{% block content %}

{% include 'partials/_alerts.html'%}

<div class="row pt-3">
	<div class="col-md-6">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="/">Home</a></li>
				<li class="breadcrumb-item active" aria-current="page">{{category|title}}</li>
			</ol>
		</nav>
	</div>	
</div>
<div class="row pb-2">
	<div class="col-md-6">
		<a role="button" href="{% url 'category-update' category.id %}" target="_blank" class="btn btn-success btn-lg text-white"><i class="fas fa-edit"></i> Edit</a>
		<a role="button" href="{% url 'category-delete' category.pk %}" target="_blank" class="btn btn-danger btn-lg ml-2"><i class="fas fa-trash-alt"></i> Delete</a>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<ul class="list-group">
		  <li 
		  {% if category.color == 'dark' or 'success' %}
		  	class="list-group-item bg-{{category.color}} text-white text-center"
		  {% else %}
		  	class="list-group-item bg-{{category.color}} text-center"
		  {% endif %}
		  >{{category|title}}</li>
		</ul>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		{% if category.todo_set.all %}
		<div class="table-responsive-sm">
			<table class="table table-striped table-hover">
			  <thead>
			    <tr>
			      <th scope="col">#</th>
			      <th scope="col"><i class="fas fa-bookmark"></i> Todo</th>
			      <th scope="col">-</th>
			      <th scope="col">-</th>
			      <th scope="col"><i class="fas fa-clock"></i> Created On</th>
			      <th scope="col">View</th>
			      <th scope="col">Edit</th>
			      <th scope="col">Delete</th>
			    </tr>
			  </thead>
			  <tbody>
			  	{% for todo in category.todo_set.all %}
				    <tr>
				      <td>{{ forloop.revcounter }}</td>
				      <td colspan="3">
				      	{% if todo.expired %}
				      		<del>{{todo.name|title}}</del> (Expired)
				      	{% elif todo.completed %}
						    {{todo.name|title}} (Completed)
						{% else %}
				      		{{todo.name|title}}
				      	{% endif %}
				      </td>

				      <td>{{ todo.start_date |date:"F d" }}</td>
				      <td><a href="{% url 'todo' todo.user todo.id %}" class="btn btn-info btn-sm"><i class="fas fa-search-plus"></i></a></td>
				      {% if todo.expired %}
				      	<td><a href="{% url 'todo-update' todo.id %}" class="btn btn-success btn-sm disabled"><i class="fas fa-edit"></i></a></td>
				      {% else %}
				      	<td><a href="{% url 'todo-update' todo.id %}" class="btn btn-success btn-sm"><i class="fas fa-edit"></i></a></td>
				      {% endif %}
				      <td><a href="{% url 'todo-delete' todo.id %}" class="btn btn-danger btn-sm" target="_blank"><i class="fas fa-trash"></i></a></td>
				    </tr>
			    {% endfor %}
			  </tbody>
			</table>
		</div>
		{% endif %}
	</div>
</div>

{% endblock %}

templates/core/category-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="col-md-6 mx-auto pt-3">
      <div class="card">
        <div class="card-header text-white bg-primary ">
          <h4 class="text-center"><i class="fas fa-edit"></i>  Update Category</h4></div>
          <div class="card-body">
            <form method="post" accept-charset="utf-8">
              {% csrf_token %}
              {{form|crispy}}
              <div class="form-group">
                <div class="mx-auto">
                  <button type="submit" class="btn btn-block btn-sm text-white bg-primary">Update</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/core/category.html
{% extends 'base.html' %}
{% block content %}

<div class="row pt-3">
	<div class="col-md-6">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="/"> Home</a></li>
				<li class="breadcrumb-item active" aria-current="page">{{request.user|title}} 's Categories</li>
			</ol>
		</nav>
	</div>	
</div>

<div class="row pb-2">
	<div class="col-md-6">
		<a role="button" href="{% url 'category-create' %}" target="_blank" class="btn btn-success btn-lg ml-2"><i class="fas fa-plus"></i> Category</a>
	</div>
</div>

		{% if categories %}
		<div class="row">
			<div class="col-md-12">
				<h2 class="text-center">Your Categories</h2>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8 mx-auto">
			<div class="list-group">
				{% for category in categories %}
					<a href="{% url 'cat' category.pk category %}" class="list-group-item list-group-item-{{category.color}} text-center">{{category|title}}  ({{category.todo_set.all.count}})</a>
				{% endfor %}
			</div>
		{% else %}
			<h1 class="display-4 text-center">No Categories Present</h1>
		{% endif %}
	</div>
</div>
{% endblock %}

templates/core/index.html
{% extends 'base.html' %}
{% block content %}



<div class="row pt-3">
	<div class="col-md-6">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="/">Home</a></li>
				<li class="breadcrumb-item active" aria-current="page"><i class="fas fa-user"></i> {{request.user|title}}'s Todo</li>
			</ol>
		</nav>
	</div>	
</div>

{% include 'partials/_alerts.html'%}

<div class="row pb-2">
	<div class="col-md-6">
		<a role="button" href="{% url 'todo-create' %}" target="_blank" class="btn btn-primary btn-lg text-white"><i class="fas fa-plus"></i> Todo</a>
		<a role="button" href="{% url 'category-create' %}" target="_blank" class="btn btn-success btn-lg ml-2"><i class="fas fa-plus"></i> Category</a>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		{% if todos %}
		<h1 class="text-center display-4 pt-1">My Todos</h1>
		<div class="table-responsive-sm">
			<table class="table table-striped table-hover">
			  <thead>
			    <tr>
			      <th scope="col">#</th>
			      <th scope="col"><i class="fas fa-bookmark"></i> Todo</th>
			      <th scope="col">-</th>
			      <th scope="col">-</th>
			      <th scope="col"><i class="fas fa-book-open"></i> Category</th>
			      <th scope="col"><i class="fas fa-clock"></i> Created On</th>
			      <th scope="col"><i class="fas fa-clock"></i> Expires On</th>
			      <th scope="col">View</th>
			      <th scope="col">Edit</th>
			      <th scope="col">Delete</th>
			    </tr>
			  </thead>
			  <tbody>
			  	{% for todo in todos %}
					    <tr>
					      <td>{{ forloop.revcounter }}</td>
					      <td colspan="3">{{todo.name|title}}</td>
					      {% if todo.category %}
					      	<td><a href="{% url 'cat' todo.category.pk todo.category %}" class="btn btn-outline-{{todo.category.color}} " role="button" aria-pressed="true">{{todo.category|title}}</a></td>
					      {% else %}
					      	<td>None</td>
					      {% endif %}
					      <td>{{ todo.start_date |date:"F d" }}</td>
					      {% if todo.end_date %}
					      	<td>{{ todo.end_date |date:"F d" }}</td>
					      {% else %}
					      	<td>None</td>
					      {% endif %}
					      <td><a href="{% url 'todo' todo.user todo.id %}" class="btn btn-info btn-sm"><i class="fas fa-search-plus"></i></a></td>
					      <td><a href="{% url 'todo-update' todo.id %}" class="btn btn-success btn-sm"><i class="fas fa-edit"></i></a></td>
					      <td><a href="{% url 'todo-delete' todo.id %}" class="btn btn-danger btn-sm" target="_blank"><i class="fas fa-trash"></i></a></td>
					    </tr>
			    {% endfor %}
			  </tbody>
			</table>
		</div>
		{% else %}
			<h4 class="text-center display-4">No Todo Available, <a href="{% url 'todo-create' %}"> Create</a> Some!!</h4>
		{% endif %}
	</div>
</div>
	
{% if completed_todo %}
	<div class="row pt-2 pb-2">
		<div class="col-md-12">
			<h1 class="text-center display-4 pt-1">Completed Todos</h1>
			<div class="table-responsive-sm">
				<table class="table table-striped table-hover">
				  <thead>
				    <tr>
				      <th scope="col">#</th>
				      <th scope="col"><i class="fas fa-bookmark"></i> Todo</th>
				      <th scope="col">-</th>
				      <th scope="col">-</th>
				      <th scope="col"><i class="fas fa-book-open"></i> Category</th>
				      <th scope="col"><i class="fas fa-clock"></i> Created On</th>
				      <th scope="col"><i class="fas fa-clock"></i> Expired On</th>
				      <th scope="col">View</th>
				      <th scope="col">Edit</th>
				      <th scope="col">Delete</th>
				    </tr>
				  </thead>
				  <tbody>
				  	{% for todo in completed_todo %}
						    <tr>
						      <td>{{ forloop.revcounter }}</td>
						      <td colspan="3">{{todo.name|title}} (Completed)</td>
						      {% if todo.category %}
						      	<td><a href="{% url 'cat' todo.category.pk todo.category %}" class="btn btn-outline-{{todo.category.color}} " role="button" aria-pressed="true">{{todo.category|title}}</a></td>
						      {% else %}
						      	<td>None</td>
						      {% endif %}
						      <td>{{ todo.start_date |date:"F d" }}</td>
						      {% if todo.end_date %}
						      	<td>{{ todo.end_date |date:"F d" }}</td>
						      {% else %}
						      	<td>None</td>
						      {% endif %}
						      <td><a href="{% url 'todo' todo.user todo.id %}" class="btn btn-info btn-sm  "><i class="fas fa-search-plus"></i></a></td>
						      <td><a href="{% url 'todo-update' todo.id %}" class="btn btn-success btn-sm"><i class="fas fa-edit"></i></a></td>
						      <td><a href="{% url 'todo-delete' todo.id %}" class="btn btn-danger btn-sm" target="_blank"><i class="fas fa-trash"></i></a></td>
						    </tr>
				    {% endfor %}
				  </tbody>
				</table>
			</div>
			
		</div>
	</div>
{% endif %}


{% if expired_todo %}
	<div class="row pt-4 pb-2">
		<div class="col-md-12">
			<h1 class="text-center display-4 pt-1">Expired Todos</h1>
			<div class="table-responsive-sm">
				<table class="table table-striped table-hover">
				  <thead>
				    <tr>
				      <th scope="col">#</th>
				      <th scope="col"><i class="fas fa-bookmark"></i> Todo</th>
				      <th scope="col">-</th>
				      <th scope="col">-</th>
				      <th scope="col"><i class="fas fa-book-open"></i> Category</th>
				      <th scope="col"><i class="fas fa-clock"></i> Created On</th>
				      <th scope="col"><i class="fas fa-clock"></i> Expired On</th>
				      <th scope="col">View</th>
				      <th scope="col">Edit</th>
				      <th scope="col">Delete</th>
				    </tr>
				  </thead>
				  <tbody>
				  	{% for todo in expired_todo %}
						    <tr>
						      <td>{{ forloop.revcounter }}</td>
						      <td colspan="3"><del>{{todo.name|title}}</del></td>
						      {% if todo.category %}
						      	<td><a href="{% url 'cat' todo.category.pk todo.category %}" class="btn btn-outline-{{todo.category.color}} " role="button" aria-pressed="true">{{todo.category|title}}</a></td>
						      {% else %}
						      	<td>None</td>
						      {% endif %}
						      <td>{{ todo.start_date |date:"F d" }}</td>
						      {% if todo.end_date %}
						      	<td>{{ todo.end_date |date:"F d" }}</td>
						      {% else %}
						      	<td>None</td>
						      {% endif %}
						      <td><a href="{% url 'todo' todo.user todo.id %}" class="btn btn-info btn-sm  "><i class="fas fa-search-plus"></i></a></td>
						      <td><a href="{% url 'todo-update' todo.id %}" class="btn btn-success btn-sm disabled"><i class="fas fa-edit"></i></a></td>
						      <td><a href="{% url 'todo-delete' todo.id %}" class="btn btn-danger btn-sm" target="_blank"><i class="fas fa-trash"></i></a></td>
						    </tr>
				    {% endfor %}
				  </tbody>
				</table>
			</div>
			
		</div>
	</div>
{% endif %}
<br><br>
{% endblock %}

templates/core/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
	Login
{% endblock %}
{% block content %}
<br>
	{% include 'partials/_alerts.html'%}
	
	<div class="row mt-3">
			<div class="col-md-6 mx-auto">
				<div class="card">
					<div class="card-header text-white bg-primary">
						<h2><i class="fas fa-user"></i>Login User</h2>
					</div>
					<div class="card-body">
						<form class="form-group" method="POST">
							{% csrf_token %}
							  <div class="form-group">
							    <label for="username">Username</label>
							    <input type="text" class="form-control" id="username" name="username" aria-describedby="usernameHelp" placeholder="Enter Username">
							    <small id="usernameHelp" class="form-text text-muted">We'll never share your username with anyone else.</small>
							  </div>
							  <div class="form-group">
							    <label for="password">Password</label>
							    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
							  </div>
							  <button type="submit" class="btn btn-sm btn-block text-white bg-primary">Submit</button>
						</form>
						<p class="text-center">Dont have an account? <a href="{% url 'register' %}"><b>Register</b></a> Instead</p>
						<p class="text-center">
						Forgotten Your Password? <a href="{% url 'reset_password' %}"><b>Reset</b></a> Here Instead</p>
					</div>
				</div>	
			</div>
		</div>
	</div>
{% endblock %}

templates/core/todo-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="col-md-6 mx-auto pt-3">
      <div class="card">
        <div class="card-header text-white bg-primary ">
          <h4 class="text-center"><i class="fas fa-edit"></i>  Update Todo</h4></div>
          <div class="card-body">
            <form method="post" accept-charset="utf-8">
              {% csrf_token %}
              {{form|crispy}}
              <div class="form-group">
                <div class="mx-auto">
                  <button type="submit" class="btn btn-block btn-sm text-white bg-primary">Update</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

{% endblock %}